# Generated by Django 5.1.4 on 2024-12-27 18:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(default='Main', max_length=100)),
                ('ifsc', models.CharField(default='DEFAULT_IFSC', max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid IFSC code', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
            ],
            options={
                'verbose_name_plural': 'Banks',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserve_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emd_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_increment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emd_submission_date', models.DateTimeField()),
                ('auction_start_date', models.DateTimeField()),
                ('auction_end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='propertyapp.bank')),
                ('property_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='propertyapp.category')),
            ],
        ),
    ]
