# Generated by Django 5.1.4 on 2025-02-16 16:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Branch', models.CharField(max_length=50)),
                ('IFSC', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid IFSC code', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
            ],
            options={
                'verbose_name_plural': 'Banks',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_Title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GoldAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appl_apac', models.CharField(max_length=100)),
                ('gross_wgt', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('state', models.CharField(max_length=100)),
                ('sub_location', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('auction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_auctions', to='propertyapp.items')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auction_id', models.CharField(max_length=10)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Location', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Reserve_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EMD_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Bid_increment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EMD_submission_date', models.DateTimeField()),
                ('Auction_start_date', models.DateTimeField()),
                ('Auction_end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('Bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='propertyapp.bank')),
                ('Property_Title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='propertyapp.category')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
