# Generated by Django 5.1.4 on 2024-12-27 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bank',
            name='ifsc',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid IFSC code', regex='^[A-Z]{4}0[A-Z0-9]{7}$')]),
        ),
    ]
