# Generated by Django 5.1.4 on 2024-12-27 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0002_alter_bank_branch_alter_bank_ifsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='ifsc',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid IFSC code', regex='[A-Z]{4}0[A-Z0-9]{6}')]),
        ),
    ]
