# Generated by Django 5.1.4 on 2024-12-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0004_property_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='branch',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='ifsc',
            new_name='IFSC',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='property_title',
            new_name='Property_Title',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='amount',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='auction_end_date',
            new_name='Auction_end_date',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='auction_id',
            new_name='Auction_id',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='auction_start_date',
            new_name='Auction_start_date',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='bank',
            new_name='Bank',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='bid_increment',
            new_name='Bid_increment',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='emd_amount',
            new_name='EMD_amount',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='emd_submission_date',
            new_name='EMD_submission_date',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_title',
            new_name='Property_Title',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='reserve_price',
            new_name='Reserve_price',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='state',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.AddField(
            model_name='property',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
